name: Chain simulator e2e tests workflow

on:
  pull_request:

jobs:
  # This job references the reusable workflow directly at the top-level `uses`
  call-reusable-workflow:
    uses: multiversx/chain-simulator-reusable-workflow/.github/workflows/workflow.yml@first-version
    with:
      with_elastic: true  # Enable Elasticsearch services
      with_notifier: false # Do not enable notifier services

  test-chainsimulator-e2e:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow  # Ensures this job waits for call-reusable-workflow
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start Docker containers
        run: |
          docker compose -f .github/docker/docker-compose.yml up -d

      # Step 1: Wait for services to be healthy
      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be healthy..."
          docker ps
          docker logs chainsimulator
          sleep 20 # Wait for 20 seconds to ensure services are up

      # Step 2: Check chainsimulator API
      - name: Check chainsimulator API
        run: |
          curl http://localhost:8085/simulator/observers

      # Step 3: Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run test:e2e
