name: Chain simulator e2e tests workflow

on:
  pull_request:

jobs:
  test-chainsimulator-e2e:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow  # Ensures this job waits for call-reusable-workflow
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      # Step 1: Call the reusable workflow to start containers
      - name: Start Docker Containers
        uses: multiversx/chain-simulator-reusable-workflow/.github/workflows/start-containers.yml@first-version
        with:
          with_elastic: true  # Enable Elasticsearch services
          with_notifier: false  # Do not enable notifier services

      # Step 2: Check chainsimulator API
      - name: Check chainsimulator API
        run: |
          curl http://localhost:8085/simulator/observers

      # Step 3: Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run test:e2e
